### ISSUE TITLE
Any plans to have new release to Maven Central?

### ISSUE THREAD

**Issue by sarxos** [xebialabs/overcast#20]
Hello @xebialabs Team,

Do you plan to have new Overcast version released to Maven Central any time soon? We are working on SNAPSHOT versions since Jun 2015 (more than 2 years now) because some important fixes has not yet been released to Central repo (but are available in the code) :( If newest code (with updated dependencies) cannot be released, then can we count on version 1.5.2 at c71236086381bd1350951c38c6f8fd707b8db03a?

I would like to have Overcast updated because new version is required in my [overcast-maven-plugin](https://github.com/sarxos/overcast-maven-plugin) which I would like to use in a demo of Overcast on the JUG event (Java Users Group meetup) so other people can learn about this awesome tool, that is the Overcast.

Please let me know it this is feasible. If not then I will have to release it on my own under my group ID, but I would really like to avoid it since I (and probably other users as well) prefer to have only one and valid source of Overcast dependencies in Maven Central.

**Comment by sarxos** [comment]
@paulvanderende, @hierynomus, can someone from @xebialabs comment on this issue, please?

**Comment by acierto** [comment]
You can point now to 10.3.0-915.1119, it is in maven central
