### ISSUE TITLE
Enable DefaultDockerClient Builder capabilities.

### ISSUE THREAD

**Issue by alex-rnv** [xebialabs/overcast#4]
Hi. It seems that there is no way to connect to docker with secured connection (which is default for boot2docker). It could be switched off, but is strictly unrecommended by them. I mean it would be great to expose details of docker client creation, to enable constructions like 
final DockerClient docker = new DefaultDockerClient.builder()
    .uri(URI.create("https://boot2docker:2376"))
    .dockerCertificates(new DockerCertificates("/Users/rohan/.docker/boot2docker-vm/"))
    .build();

**Comment by MarWestermann** [comment]
Hi, I have the same problem beeing not able to use overcast in conjunction with boot2docker on windows.

**Comment by ensonik** [comment]
Agreed. This is a complete show stopper for us right now (we're in a mixed environment). Although exposing the full capability of ```DefaultDockerClient``` would be nice, I would settle for good Boot2Docker compatability. This could include:
- certificate location;
- a plugable way of finding out what the b2d ip is. Putting 127.0.0.0 in the dockerHost variable doesn't cut it when running through Boot2Docker (I mean in a team environment where people run different OS's on their workstations)

**Comment by rklaren** [comment]
@alex-rnv Does the new <host>.certificates setting suffice (thanks @reta !) or does more of the builder need to be exposed? E.g. custom certificate locations and such ?

**Comment by alex-rnv** [comment]
I think this will suffice. At least boot2docker show stopper is resolved. But for the second problem from @ensonik message above, one more option should be exposed (at least this is the only solution I know): 
`docker --hostname=mydockeredapplication`
In DockerClient builder it looks like:
`ContainerConfig.Builder configBuilder = ContainerConfig.builder();
configBuilder.hostname(dockerHost.getHostname());`
I can add this in separate PR, if you want.

**Comment by reta** [comment]
Hey @alex-rnv, I think with this PR https://github.com/xebialabs/overcast/pull/18 incorporated a few days ago into master (thanks @rklaren!) you should be in a good shape. Latest Docker Client by default is able to figure out all Docker parameters from environment variables (DOCKER_HOST, DOCKER_CERTIFICATES, ....) so no need to repeat them explicitly. Would you mind to give it a try? 

Thanks!

**Comment by rklaren** [comment]
@alex-rnv a PR for configuring the hostname in the container would be nice. I wonder though if that would solve the figuring out the b2d ip? The hostname option only changes the hostname inside the container does it ? 

The current implementation of the DockerHost.getHostName() will return the IP/hostname of the docker host. So that should be the IP of the b2d ?

In a sense this is inconsistent with how the other CloudHost implementations work, I'd more expect it to inspect the container and return it's IP. Although it depends a lot on how networking is setup if that is actually useful.
