### ISSUE TITLE
Upgrade Docker Client to newer one

### ISSUE THREAD

**Issue by sarxos** [xebialabs/overcast#6]
Hello @xebialabs team,

Overcast is using pretty old Docker Client which disallow use of Unix socket when communicating with Docker REST interface. The one currently used is `2.4.2` but I verified `2.7.6` to work perfectly well. By overriding this dependency with newer one I was able to spawn new containers without reconfiguring my Docker daemon to listen on TCP port. Also, with newer Docker Client my Overcast configuration utilizes `unix://` socket protocol and working just fine without any additional changes in the Overcast code.

Example:

``` plain
mysql {
    dockerHost="unix:///var/run/docker.sock"
    dockerImage="mysql:5.6"
    exposeAllPorts=true
    remove=true
    env=["MYSQL_ROOT_PASSWORD=foo","MYSQL_USER=root","MYSQL_DATABASE=bar"]
    command=["mysqld"]
}
```

Please consider upgrading to newer Docker Client.

**Comment by rklaren** [comment]
Just upgraded to the latest.
