### ISSUE TITLE
Release roadmap

### ISSUE THREAD

**Issue by sarxos** [xebialabs/overcast#7]
Hi,

Is there any plan or roadmap of when users can expect newer Overcast versions to be released into the Maven Central?

**Comment by rklaren** [comment]
No real plan, usually releases happen as we (XebiaLabs) need them, we make extensive use of the library for integration tests. Of course when an interesting pull request get's merged we'll release as well.

Cheers,

Ric

**Comment by sarxos** [comment]
Ok, good to know. Thank you!
